# This rule is not used by the project previewd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over preview.previewd.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: previewd
    app.kubernetes.io/managed-by: kustomize
  name: previewenvironment-admin-role
rules:
- apiGroups:
  - preview.previewd.io
  resources:
  - previewenvironments
  verbs:
  - '*'
- apiGroups:
  - preview.previewd.io
  resources:
  - previewenvironments/status
  verbs:
  - get
