# This rule is not used by the project previewd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to preview.previewd.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: previewd
    app.kubernetes.io/managed-by: kustomize
  name: previewenvironment-viewer-role
rules:
- apiGroups:
  - preview.previewd.io
  resources:
  - previewenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - preview.previewd.io
  resources:
  - previewenvironments/status
  verbs:
  - get
