apiVersion: preview.previewd.io/v1alpha1
kind: PreviewEnvironment
metadata:
  labels:
    app.kubernetes.io/name: previewd
    app.kubernetes.io/managed-by: kustomize
  name: previewenvironment-sample
spec:
  # TODO(user): Add fields here
